one commit per it :
correct :
expect(range.getHands().length).toEqual(169)
AssertionError: expected +0 to deeply equal 169

dumb loop of 169 it with the same card